site_name: Geo Activity Playground
site_url: 'https://martin-ueding.github.io/geo-activity-playground/'

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      media: "(prefers-color-scheme: light)"
    - scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      media: "(prefers-color-scheme: dark)"

nav:
  - index.md
  - Getting Started:
      - getting-started/installing-stable-on-linux.md
      - getting-started/installing-stable-on-windows.md
      - getting-started/installing-git-on-linux.md
      - getting-started/docker.md
      - getting-started/docker-compose-tailscale.md
      - getting-started/using-activity-files.md
      - getting-started/using-strava-api.md
      - getting-started/moving-from-strava.md
      - getting-started/starting-the-webserver.md
  - Features:
      - features/overview.md
      - features/activity-view.md
      - features/calendar.md
      - features/heatmaps.md
      - features/explorer-tiles.md
      - features/eddington.md
      - features/equipment.md
      - features/upload.md
      - features/share-picture.md
  - Reference:
      - reference/changelog.md
  - acknowledgments.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
